# Generated by Django 5.0.3 on 2024-03-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_acessorio_cor_veiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name_plural': 'Cores'},
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
