# Generated by Django 5.0.3 on 2024-04-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cor_options_veiculo_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
