# Generated by Django 5.0.3 on 2024-04-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_veiculo_acessorios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='acessorios',
            field=models.ManyToManyField(blank=True, default=[], null=True, related_name='veiculos', to='core.acessorio'),
        ),
    ]
